name: biospark
channels:
  - defaults
  - conda-forge
  - plotly
dependencies:
  - python
  - pandas
  - numpy
  - ipykernel
  - matplotlib
  - plotly
  - jupyter
  - jupyterlab
  - jupyterlab-plotly-extension
  - dash>2.9
  - python-kaleido
  - scipy
  - seaborn
  - statsmodels
  - scikit-learn
  - tqdm
